baseURL = 'https://www.nikolalukovic.com'
defaultContentLanguage = "en"
title = "A Blog"
theme = "gokarna"

enableRobotsTXT = true
pygmentsStyle = "monokai"

[params]
footer = "Nikola Luković"
description = "Code · Architecture · Design"
avatarURL = "https://avatars.githubusercontent.com/u/6897673?v=4"
avatarSize = "size-m"
customHeadHTML = '''
    <script defer data-domain="nikolalukovic.com" src="https://plausible.io/js/plausible.js"></script>
'''
showPostsOnHomePage = "recent"
metaKeywords = [
    "blog",
    "software",
    "nlukovic",
    "nikolalukovic",
    "programming",
    "react",
    "js",
    "javascript",
    "css",
    "html",
    "go",
    "golang",
    ".net",
    "dotnet",
    "dotnetcore",
    "aspnetcore",
    "itekako",
    "nikola",
    "lukovic",
    "luković",
    "nikola lukovic",
    "nikola luković",
    "nikola.lukovic",
    "nikola.lukovic@live.com"
]

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "posts"
url = "/posts/"
name = "Posts"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
identifier = "github"
url = "https://github.com/nikolalukovic"
weight = 4
pre = "<span data-feather='github'></span>"

[[menu.main]]
identifier = "linkedin"
url = "https://www.linkedin.com/in/nikola-lukovic-89a17595"
weight = 5
pre = "<span data-feather='linkedin'></span>"

[[menu.main]]
identifier = "mastodon"
pre = "<span data-feather='external-link'></span>"
url = "https://hachyderm.io/@nikola"
weight = 6

[[menu.main]]
identifier = "twitter"
pre = "<span data-feather='twitter'></span>"
url = "https://twitter.com/Kooraiber"
weight = 7

[[menu.main]]
identifier = "bandcamp"
pre = "<span data-feather='music'></span>"
url = "https://bandcamp.com/nikolalukovic"
weight = 8
